### ISSUE TITLE
No 'Host' header specified when sending request to https://[ipv6]/api/v1/cluster/me/version

### ISSUE THREAD

**Issue by qoutland** [rubrikinc/rubrik-sdk-for-python#168]
**Expected Behavior**

When rubrik_cdm.bootstrap.setup_cluster() sends a GET request to https://[ipv6]/api/v1/cluster/me/version from a remote client, the version is returned in json format.

**Current Behavior**

There is a terminal error when sending the GET packet that there is no 'Host' Header in the GET packet.

**Failure Information (for bugs)**

When debug is turned on the error is returned that No Host header is specified.

* Use verbose outputs to capture any debug information:
```
[2019-10-23 16:49:09,890] [DEBUG] -- <Response [400]>

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rubrik_cdm-2.0.5-py3.5.egg/rubrik_cdm/api.py", line 140, in _common_api
  File "/usr/local/lib/python3.5/dist-packages/requests-2.21.0-py3.5.egg/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rubrik_cdm-2.0.5-py3.5.egg/rubrik_cdm/api.py", line 148, in _common_api
  File "/usr/local/lib/python3.5/dist-packages/requests-2.21.0-py3.5.egg/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://[ipv6]/api/v1/cluster/me/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./configure.py", line 24, in <module>
    node_config, enable_encryption=False)
  File "/usr/local/lib/python3.5/dist-packages/rubrik_cdm-2.0.5-py3.5.egg/rubrik_cdm/rubrik_cdm.py", line 402, in setup_cluster
  File "/usr/local/lib/python3.5/dist-packages/rubrik_cdm-2.0.5-py3.5.egg/rubrik_cdm/api.py", line 202, in get
  File "/usr/local/lib/python3.5/dist-packages/rubrik_cdm-2.0.5-py3.5.egg/rubrik_cdm/api.py", line 162, in _common_api
rubrik_cdm.exceptions.APICallException: Request is missing required `Host` header
```

**Steps to Reproduce**

* Follow the script here: https://rubrik.gitbook.io/rubrik-sdk-for-python/bootstrap-functions/setup_cluster for virtual appliance.
* Enter the ipv6 address and interface
* Run the script from a remote machine

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project: rubrik-va-5.0.3-p1-2299.ova
* Version of dependencies:
```
certifi==2019.9.11
chardet==3.0.4
command-not-found==0.3
idna==2.8
language-selector==0.1
pi==0.1.2
pycurl==7.43.0
pygobject==3.20.0
python-apt==1.1.0b1+ubuntu0.16.4.5
python-dateutil==2.8.0
python-debian==0.1.27
python-systemd==231
pytz==2019.3
requests==2.21.0
rubrik-cdm==2.0.5
six==1.12.0
ssh-import-id==5.5
ufw==0.35
unattended-upgrades==0.1
urllib3==1.24.3
```
* Version of operating system: Ubuntu 18.04

**Failure Logs**

Please include any relevant log snippets or files here.

Already included above.

**Comment by drew-russell** [comment]
@qoutland thanks for reporting. We will dig into it.

**Comment by drew-russell** [comment]
@qoutland any chance you can provide an example of your code?

Trying to better understand this line in your log file `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://[ipv6]/api/v1/cluster/me/version`

Specifically, the `[ipv6]` portion.
`
