### ISSUE TITLE
Add ability to pass dictionary of URL parameters

### ISSUE THREAD

**Issue by railroadmanuk** [rubrikinc/rubrik-sdk-for-python#26]
**What would you like to be added**:

Add the ability to pass a dictionary of parameters to the `get`, `post`, `patch` etc endpoints, rather than adding these to the URL.

**Why is this needed**:

Simpler than forming query strings in URL.

**Comment by drew-russell** [comment]
@railroadmanuk do you have an example in mind? Don't need anything fancy just want to make sure I understand the request.

**Comment by railroadmanuk** [comment]
Sure. Right now we do this to request events of a certain type:

```python
rubrik.get('internal','event?status=Failure&event_type=Backup&limit=200&object_type=VmwareVm')
```

Instead we could set our params and simplify the call.

```python
PARAMS={
  'status':'Failure',
  'limit':'200',
  'event_type':'Backup',
  'object_type':'VmwareVm'
}
rubrik.get('internal','event',params=PARAMS)
```

This would make it far more efficient to pass large numbers of parameters, and less prone to error

**Comment by geluyan** [comment]
I was able to test the adjustments with an optional dict parameter but I'm having trouble updating the documentation with docs/create_docs.py.

```
andys-mbp-3:docs Andy$ python create_docs.py
Traceback (most recent call last):
  File "create_docs.py", line 5, in <module>
    import reprlib
```

I've changed the import to `import repr as reprlib`

```
andys-mbp-3:docs Andy$ python create_docs.py
Traceback (most recent call last):
  File "create_docs.py", line 266, in <module>
    del base_api_functions[0]
IndexError: list assignment index out of range
```

I'd like to get this done before I create a pull request. Does someone have an idea?
