### ISSUE TITLE
create_user and end_user_authorization fail on CDM 5.3

### ISSUE THREAD

**Issue by achimgorski** [rubrikinc/rubrik-sdk-for-python#273]
Create User Example:
https://rubrik.gitbook.io/rubrik-sdk-for-python/cluster-functions/create_user

Fails: 
____________

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 140, in _common_api
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 153, in _common_api
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://10.225.9.10/api/internal/user?username=testuser12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./add_user.py", line 29, in <module>
    create_user = rubrik.create_user(username, password)
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/cluster.py", line 877, in create_user
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 228, in get
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 168, in _common_api
rubrik_cdm.exceptions.APICallException: Undefined API

###################################################

End User Authorization:
https://rubrik.gitbook.io/rubrik-sdk-for-python/cluster-functions/end_user_authorization

Fails:
________________

raceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 140, in _common_api
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 153, in _common_api
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://10.225.9.10/api/internal/user?username=testuser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./user_auth.py", line 29, in <module>
    authorize = rubrik.end_user_authorization(vm_name, end_user_name)
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/cluster.py", line 273, in end_user_authorization
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 228, in get
  File "/usr/local/lib/python3.6/site-packages/rubrik_cdm-2.0.10-py3.6.egg/rubrik_cdm/api.py", line 168, in _common_api
rubrik_cdm.exceptions.APICallException: Undefined API

**Comment by berndholtkamp** [comment]
pmilano1: will it be possible to manage users and roles via python-sdk without using polaris?
