### ISSUE TITLE
SDK 1.0.12 does not install on Ubuntu 18.04 with Python 3.6.7

### ISSUE THREAD

**Issue by illyaAtEpic** [rubrikinc/rubrik-sdk-for-python#54]
Trying to install in a Docker container running Ubuntu 18.04 with Python 3.6.7 but the package does not install. It works perfectly with SDK version 1.0.11. 

Error:
```
Collecting rubrik_cdm
  Downloading https://artifactory.test.lab:8443/artifactory/api/pypi/pypi/packages/a6/66/54064a3beedff2432aaf11ba4703ce9138f81a5a3a4450df48fbfa8c722d/rubrik_cdm-1.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jqorcfbr/rubrik-cdm/setup.py", line 6, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1132: ordinal not in range(128)
```

**Comment by drew-russell** [comment]
@illyaAtEpic Looks like this is related to the encoding languages. 

Can you update your `Dockerfile` with:

```
ENV LC_CTYPE en_US.UTF-8
ENV LANG en_US.UTF-8
```

Or you can manually add the environment variables to the `~/.bashrc` and` ~/.profile`:

```
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
```

I was able to validate this with the following `Dockerfile`:

```
FROM ubuntu:18.04

ENV LC_CTYPE en_US.UTF-8
ENV LANG en_US.UTF-8

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    language-pack-en \
    python3 \
    python3-pip \
    python3-dev \
    && pip3 --no-cache-dir install --upgrade \
    setuptools \
    wheel \
    && pip3 install rubrik-cdm
```

**Comment by drew-russell** [comment]
@illyaAtEpic I am going to close out this issue as resolved. Please let me know if you have any problems though.
